# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 177d8e9d9c7cb34dfa1dccbe8bd8e3425560610da2cb9aa0d3ccc6e9ab1cc60522938c340e8a096de34927775bd9c77204c91fe0d498aea08c3a9f7aec6cf70b

test:
  secret_key_base: eca1380778a5eb5c45d69b5879f89079b1e56f1147443c400053e257531a8fdb6a264e0d8e60d1c1bf3cb1e902d47c93a3b0f2a25df92b60cca39515d6eda062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
